"""
T2 SFT, which fine-tunes the tutor on SocraTeach dialogues with the loss taken over the
teacher turns only.

Run `uv run sft --help` for the options.
"""

import argparse
import json
import logging
import os
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    PreTrainedTokenizerBase,
    Trainer,
    TrainerCallback,
    TrainingArguments,
)

from its.config import (
    EVAL_SAMPLES_PATH,
    SOCRATEACH_TRAIN_PATH,
    SOCRATEACH_VAL_PATH,
    T2_DIR,
    TUTOR_MODEL_ID,
)
from its.llm import apply_template

log = logging.getLogger(__name__)

# --- Dataset -------------------------------------------------------------------


@dataclass
class _Example:
    input_ids: torch.Tensor
    labels: torch.Tensor
    attention_mask: torch.Tensor


def _tokenize(tokenizer: PreTrainedTokenizerBase, messages: list[dict], max_length: int) -> _Example | None:
    full_ids: list[int] = apply_template(tokenizer, messages, add_generation_prompt=False)

    if len(full_ids) > max_length:
        return None

    # The labels are -100 for all tokens except those generated by the assistant
    labels = [-100] * len(full_ids)
    for i, msg in enumerate(messages):
        if msg["role"] != "assistant":
            continue
        prefix_ids = apply_template(tokenizer, messages[:i], add_generation_prompt=True)
        incl_ids = apply_template(tokenizer, messages[:i + 1], add_generation_prompt=False)
        start, end = len(prefix_ids), len(incl_ids)
        labels[start:end] = full_ids[start:end]

    # If there are no assistant turns, the labels are all -100 and the example is useless for SFT
    if all(l == -100 for l in labels):
        return None

    return _Example(
        input_ids=torch.tensor(full_ids, dtype=torch.long),
        labels=torch.tensor(labels, dtype=torch.long),
        attention_mask=torch.ones(len(full_ids), dtype=torch.long),
    )


class SocraTeachDataset(Dataset):
    """
    Dataset of SocraTeach Socratic dialogues, tokenized for SFT.
    """

    def __init__(self, path: Path, tokenizer: PreTrainedTokenizerBase, max_length: int, max_examples: int = -1) -> None:
        self._examples: list[_Example] = []

        lines = [l for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]

        # Tokenize each example, skipping those that are too long or have no assistant turns.
        skipped = 0
        for line in lines:
            if max_examples != -1 and len(self._examples) >= max_examples:
                break
            ex = _tokenize(tokenizer, json.loads(line)["messages"], max_length)
            if ex is None:
                skipped += 1
            else:
                self._examples.append(ex)

        log.info(
            "Dataset: %d examples loaded, %d skipped (too long or no assistant turns).",
            len(self._examples),
            skipped,
        )

    def __len__(self) -> int:
        return len(self._examples)

    def __getitem__(self, i: int) -> dict:
        ex = self._examples[i]
        return {"input_ids": ex.input_ids, "labels": ex.labels, "attention_mask": ex.attention_mask}


class _PaddingCollator:

    def __init__(self, pad_id: int) -> None:
        self._pad_id = pad_id

    def __call__(self, batch: list[dict]) -> dict:
        max_len = max(x["input_ids"].shape[0] for x in batch)

        def padded(key: str, fill: int) -> torch.Tensor:
            """
            Every sequence in the batch right-padded to max_len, stacked into one tensor.
            """
            return torch.stack([F.pad(x[key], (0, max_len - x[key].shape[0]), value=fill) for x in batch])

        # Each field pads with a different filler. -100 keeps the padding out of the loss,
        # and 0 keeps it out of the attention.
        return {
            "input_ids": padded("input_ids", self._pad_id),
            "labels": padded("labels", -100),
            "attention_mask": padded("attention_mask", 0),
        }


@contextmanager
def _generation_mode(model):
    """
    Puts the model in eval with its cache on, and restores whatever was there before.
    Gradient checkpointing turns the cache off, and generate() needs it back.
    """
    was_training = model.training
    old_use_cache = getattr(model.config, "use_cache", True)
    model.eval()
    model.config.use_cache = True
    try:
        yield
    finally:
        model.config.use_cache = old_use_cache
        if was_training:
            model.train()


class _GenerationLoggerCallback(TrainerCallback):
    """
    Logs a few sample generations to wandb at the start of training and after each eval.
    """

    def __init__(
        self,
        tokenizer: PreTrainedTokenizerBase,
        samples: list[list[dict]],
        max_new_tokens: int = 200,
    ) -> None:
        self._tokenizer = tokenizer
        self._samples = samples
        self._max_new_tokens = max_new_tokens
        # History of all generations so far
        self._rows: list[list] = []
        # To avoid double-logging
        self._logged_steps: set[int] = set()

    def _generate_and_log(self, state, model):
        if model is None or not state.is_world_process_zero:
            return
        if state.global_step in self._logged_steps:
            return
        try:
            import wandb
        except ImportError:
            return

        with _generation_mode(model):
            for messages in self._samples:
                try:
                    generated = self._generate(model, messages)
                except Exception as e:
                    log.warning("Sample generation failed: %s", e)
                    generated = f"<error: {e}>"

                last_user = next((m["content"] for m in reversed(messages) if m["role"] == "user"), "")
                self._rows.append([state.global_step, last_user, generated])

        self._logged_steps.add(state.global_step)
        wandb.log({"samples": wandb.Table(
            columns=["step", "last_user_msg", "generated"],
            data=list(self._rows),
        )})

    def _generate(self, model, messages: list[dict]) -> str:
        """
        Generates a response from the model given a list of messages.
        """
        inputs: Any = self._tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=True,
            return_tensors="pt",
            return_dict=True,
        )
        inputs = inputs.to(model.device)
        input_len = inputs["input_ids"].shape[-1]

        with torch.no_grad():
            out = model.generate(**inputs, max_new_tokens=self._max_new_tokens, do_sample=False)

        return self._tokenizer.decode(out[0, input_len:], skip_special_tokens=True).strip()

    def on_train_begin(self, args, state, control, model=None, **kwargs):
        self._generate_and_log(state, model)

    def on_evaluate(self, args, state, control, model=None, **kwargs):
        self._generate_and_log(state, model)


def _load_eval_samples(path: Path) -> list[list[dict]]:
    """
    Loads a list of SocraTeach samples for generation logging.
    """
    if not path.exists():
        return []

    samples: list[list[dict]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        samples.append(json.loads(line)["messages"])

    return samples


# --- Entry point ---------------------------------------------------------------


def _optional_path(value: str) -> Path | None:
    return Path(value) if value else None


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="T2 SFT training")
    p.add_argument("--model", default=TUTOR_MODEL_ID, help="HuggingFace model ID")
    p.add_argument("--train-data", type=Path, default=SOCRATEACH_TRAIN_PATH, help="Train JSONL")
    p.add_argument("--val-data",
                   type=_optional_path,
                   default=SOCRATEACH_VAL_PATH,
                   help="Val JSONL (disable eval with --val-data '')")
    p.add_argument("--output", type=Path, default=T2_DIR)
    p.add_argument("--epochs", type=int, default=3)
    p.add_argument("--batch-size", type=int, default=4)
    p.add_argument("--grad-accum", type=int, default=4)
    p.add_argument("--lr", type=float, default=2e-4)
    p.add_argument("--max-length", type=int, default=2048)
    p.add_argument("--max-steps", type=int, default=-1, help="Stop after N steps (-1 = full training)")
    p.add_argument("--max-examples", type=int, default=-1, help="Tokenize at most N examples (-1 = all)")
    p.add_argument("--save-steps", type=int, default=500, help="Save a (resumable) checkpoint and eval every N steps")
    p.add_argument("--resume", action="store_true", help="Resume from the latest checkpoint in --output, if one exists")
    p.add_argument("--overwrite", action="store_true", help="Train into --output even if it already holds a run")
    p.add_argument("--no-wandb", action="store_true", help="Disable wandb logging")
    args = p.parse_args()

    if args.output.exists() and any(args.output.iterdir()) and not (args.resume or args.overwrite):
        raise SystemExit(f"{args.output} is not empty. Pass --resume to continue that run, "
                         f"--overwrite to replace it, or --output to train somewhere else.")
    return args


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(levelname)-8s  %(message)s")
    args = _parse_args()

    if not args.no_wandb:
        os.environ["WANDB_PROJECT"] = "ITS SFT"

    log.info("Loading %s ...", args.model)
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForCausalLM.from_pretrained(args.model, dtype="auto", device_map="auto")

    log.info("Tokenizing train: %s", args.train_data)
    train_ds = SocraTeachDataset(args.train_data, tokenizer, max_length=args.max_length, max_examples=args.max_examples)

    val_ds: SocraTeachDataset | None = None
    if args.val_data is None:
        log.info("No val data, so eval and best-checkpoint tracking are disabled.")
    elif not args.val_data.exists():
        log.warning("Val data %s does not exist, so eval and best-checkpoint tracking are disabled.", args.val_data)
    else:
        log.info("Tokenizing val: %s", args.val_data)
        val_ds = SocraTeachDataset(args.val_data, tokenizer, max_length=args.max_length, max_examples=args.max_examples)

    pad_id = tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
    use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()

    eval_kwargs: dict = {}
    if val_ds is not None:
        eval_kwargs = dict(
            eval_strategy="steps",
            eval_steps=args.save_steps,
            per_device_eval_batch_size=args.batch_size,
            load_best_model_at_end=True,
            metric_for_best_model="eval_loss",
            greater_is_better=False,
        )

    training_args = TrainingArguments(
        output_dir=str(args.output),
        max_steps=args.max_steps,
        num_train_epochs=args.epochs if args.max_steps == -1 else 1,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        warmup_steps=50,
        lr_scheduler_type="cosine",
        bf16=use_bf16,
        fp16=not use_bf16 and torch.cuda.is_available(),
        gradient_checkpointing=True,
        logging_steps=1,
        save_strategy="steps",
        save_steps=args.save_steps,
        save_total_limit=2,
        save_only_model=False,
        report_to="none" if args.no_wandb else "wandb",
        **eval_kwargs,
    )

    callbacks: list[TrainerCallback] = []
    if not args.no_wandb:
        gen_samples = _load_eval_samples(EVAL_SAMPLES_PATH)
        if gen_samples:
            log.info("Logging %d generation samples per eval (from %s)", len(gen_samples), EVAL_SAMPLES_PATH)
            callbacks.append(_GenerationLoggerCallback(tokenizer, gen_samples))

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        data_collator=_PaddingCollator(pad_id),
        callbacks=callbacks or None,
    )

    resume = args.resume and any(args.output.glob("checkpoint-*"))
    log.info("Training ... (resume=%s)", resume)
    trainer.train(resume_from_checkpoint=resume)

    log.info("Saving → %s", args.output)
    trainer.save_model(str(args.output))
    tokenizer.save_pretrained(str(args.output))
    log.info("Done.")
